---
title: "MARS Documentation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mars}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE}
library(KTPmars)
```

<p>

Mars Function:

```{r}
mc <- mars.control(Mmax = 10)
concretemars <-mars(ConcreteCompressiveStrength~.,data=concrete,control = mc)
toxicmars <-mars(LC50~.,data=fishToxicity, control = mc)
yachtmars <-mars(RRPUWOD~.,data=yacht, control = mc)
```

<p>

Summary Function:

```{r}
summary(concretemars)
summary(toxicmars)
summary(yachtmars)
```

<p>

Print Function:

```{r}
print(concretemars)
print(toxicmars)
print(yachtmars)
```

<p>

Predict Function:

```{r}
predict(concretemars)
predict(toxicmars)
predict(yachtmars)
```

<p>

Anova Function:

```{r}
anova(concretemars)
anova(toxicmars)
anova(yachtmars)
```

<p>

Plot Function:

```{r, fig.width=8, fig.height=4}
plot(concretemars)
plot(toxicmars)
plot(yachtmars)
```
